### PR TITLE
Remove evaluation steps

### LINKED ISSUE #8: Get AidUI Docker Running Without Error
Related User Story: #7

This task involves getting the docker image working while removing the evaluation steps that are causing errors.

Estimated Effort: This task will require significant effort as evaluation takes up a significant portion of the code base, and commenting out code while keeping AidUI in working condition will take effort.

Dependencies: None

Initial Assignments: @libioco 

Milestone: Sprint 1

Acceptance Criteria: AidUI runs without errors.

### PR DESCRIPTION
**Pull request by libioco**
Comment out lines 8, 65-70, and 95 according to Dr. Moran's guidance from office hours. This pull request combines all team members' cumulative effort.

### CODE REVIEW

**Comment by libioco** [comment]
Removing the evaluation steps (commit d11971c) avoids the point of entry for some of the Python errors we were receiving when running AidUI before making any changes, most of it being `Object Not Iterable` errors. While this does not fix the error itself, we avoid the error. This commit does have value to #8.

**Comment by libioco** [comment]
We removed excess images from the dataset (commit 4a4eff8) to leave behind one image: `(345)www.harveynorman.sg_3146.jpg`. This allowed me to run AidUI to make sure it was not having errors and also while testing with only a single image. While we did not get any output showing a bounding box around the dark pattern, the program ran without errors. For that reason, this commit has value to #8 and #9.

**Comment by StudentJamesChen** [comment]
**Input Image:**
image

**Output JSON file:**
image

**Review by SamarKaranch — APPROVED** [review]
Looks good to me! I manually tested it for you, the error we previously ran into is no longer there as it has been commented out through evaluation steps. AID-UI now outputs a json file, but it doesn't have any bounding boxes in it. 

Overall you have made good progress on this

**Pull request merged**
